// Generated by JackTheEnumRipper
// Source: Secrets of Grindea: SoG\TreasureMapEntry\TreasureMapID
// Game Version: 1.00
public enum SogTreasureMap : ushort
{
    Null = 0,
    TreasureMap01 = 1000,
    TreasureMap02 = 1001,
    TreasureMap03 = 1002,
    TreasureMap04 = 1003,
    TreasureMap05 = 1004,
    TreasureMap06 = 1005,
    TreasureMap07 = 1006,
    TreasureMap08 = 1007,
    TreasureMap09_Fertilizer = 1008,
    TreasureMap10_Ugras = 1009,
    TreasureMap11_PhasemanBoots_39 = 1010,
    TreasureMap12_Antlers_19 = 1011,
    TreasureMap13_PlantBladeSeed_22 = 1012,
    TreasureMap14_Diamond_40 = 1013,
    TreasureMap15_FunnyMask_41 = 1014,
    TreasureMap16_Salamander_34 = 1015,
    SpecialMap02_Tessen = 1,
    FinderMap01 = 2,
    FinderMap02 = 3,
    FinderMap03 = 4,
}